In [118]:
# 4

import numpy as np
import numpy.random

np.random.seed(151)
def Cholesky(n):
    b = np.random.normal(size=n)
    gamma = np.random.uniform(size=n)
    alpha = gamma+1
    gamma[0] = 0

    l = np.zeros(n)
    l[0] = alpha[0]
    for i in range(1,n):
        l[i] = alpha[i] - gamma[i]**2 / l[i-1]
    l = np.sqrt(l)
    v = gamma[1:] / l[:-1]
    v = np.insert(v,0,0)

    # Solve Ly=b: confirmed to work
    y = [b[0]/l[0]]
    for i in range(1,n):
        y.append((b[i]-y[-1]*v[i])/l[i])
    
    # Solve L^Tx=y: confirmed to work
    x = np.zeros(n)
    x[n-1] = y[n-1]/l[n-1]
    for i in range(n-2,-1,-1):
        x[i] = (y[i]-x[i+1]*v[i+1])/l[i]

    # Calculate Ax:
    b2 = np.zeros(n)
    for i in range(1,n-1):
        b2[i] = gamma[i]*x[i-1] + alpha[i]*x[i] + gamma[i+1]*x[i+1]
    b2[0] = alpha[0]*x[0]+gamma[1]*x[1]
    b2[-1] = gamma[-1]*x[-2]+alpha[-1]*x[-1]
    
    return np.max(np.abs(b2-b))



#print("n=10: {}".format(Cholesky(10)))
#Cholesky(10)
for N in [10,100,1000,10000]:
    print("Infinity norm of error for N = {}: {}".format(N,Cholesky(N)))



Infinity norm of error for N = 10: 1.1102230246251565e-15
Infinity norm of error for N = 100: 2.6645352591003757e-15
Infinity norm of error for N = 1000: 1.1102230246251565e-15
Infinity norm of error for N = 10000: 2.9976021664879227e-15


In [261]:
# 9
A1 = np.array([[-0.897,-1.004,-0.284,0.822],
                [1.066,-0.484,-1.327,-0.679],
                [1.33,1.37,-0.878,0.678],
                [1.368,0.669,-0.392,0.221],
                [-0.964,0.84,1.497,-0.427]])
b1 = np.array([-0.847,-0.829,-0.579,0.831,-1.088])


def SolveLSQR(A,b):
    m,n=A.shape
    v = np.zeros((m,n))
    A = np.vstack([A,np.zeros(n)])

    for j in range(n):
        x = A[j:m,j]
        A[j+1:,j] = np.sign(x[0])*np.linalg.norm(x,2)*np.eye(1,m-j,0)+x
        A[j+1:,j] /= np.linalg.norm(A[j+1:,j],2)
        A[j:m,j:]=A[j:m,j:]-2*np.outer(A[j+1:,j],np.matmul(A[j+1:,j],A[j:m,j:]))
        print(A)

    # y = QTb:
    y = np.zeros(n)
    for j in range(n):
        y[j] = b[:m-j].dot(A[j+1:,j])

    # Rx=y: this part is confirmed to work
    x = np.zeros(n)
    x[n-1] = y[n-1]/A[n-1,n-1]
    for j in range(n-2,-1,-1):
        x[j] = (y[j]-x[j+1:].dot(A[j,j+1:]))/A[j,j]
    print(x)
    
SolveLSQR(A1,b1)




[[ 0.15112678  0.90617251 -1.68794625  0.06056942]
 [-1.14604309 -1.07445783 -0.89302294 -0.44363244]
 [-0.15011922  0.63331247 -0.33654644  0.97165747]
 [-0.09873771 -0.08873575  0.16492366  0.52304768]
 [ 0.6190842   1.37395999  1.10454795 -0.63984646]
 [-0.22979289  0.          0.          0.        ]]
[[ 0.15112678  0.90617251 -1.68794625  0.06056942]
 [-1.14604309  0.28953842  1.21079962  0.08962018]
 [-0.15011922 -1.18296457 -0.79094235  0.85648245]
 [-0.09873771  0.23315138  0.22859075  0.53918528]
 [ 0.6190842  -0.66602193  0.1187442  -0.8897166 ]
 [-0.22979289  0.41626575  0.          0.        ]]
[[ 0.15112678  0.90617251 -1.68794625  0.06056942]
 [-1.14604309  0.28953842  1.21079962  0.08962018]
 [-0.15011922 -1.18296457  0.50051677 -0.79321848]
 [-0.09873771  0.23315138 -1.169555    0.77156908]
 [ 0.6190842  -0.66602193  0.04462166 -0.76900205]
 [-0.22979289  0.41626575  0.07226878  0.        ]]
[[ 0.15112678  0.90617251 -1.68794625  0.06056942]
 [-1.14604309  0.28953842  1

In [260]:
A = np.array([[-0.897,-1.004,-0.284,0.822],
                [1.066,-0.484,-1.327,-0.679],
                [1.33,1.37,-0.878,0.678],
                [1.368,0.669,-0.392,0.221],
                [-0.964,0.84,1.497,-0.427]])
b = np.array([-0.847,-0.829,-0.579,0.831,-1.088])

n=4
m=5
v = np.zeros((m,n))

test = np.arange(1,10)

#print(A)
for j in range(n):
    x = A[j:,j]
    #print(v)
    #print(v[:n-j,j])
    v[:m-j,j] = np.sign(x[0])*np.linalg.norm(x,2)*np.eye(1,m-j,0)+x
    v[:m-j,j] /= np.linalg.norm(v[:m-j,j],2)
    #print(v[:,j].reshape(-1,1))
    #print(A[j:,j:])
    #print(np.matmul(v[:,j],A[j:,j:]))
    #print(np.outer(v[:,j],np.matmul(v[:,j],A[j:,j:])))
    A[j:,j:]=A[j:,j:]-2*np.outer(v[:m-j,j],np.matmul(v[:m-j,j],A[j:,j:]))
    #print(A)
print(A)
print(v)
y=v.T@b
print(y)
x = np.linalg.solve(A[:-1,:],y)
print(x)

actual = np.linalg.inv(A1.T@A1)@A1.T@b1
print(actual)



[[ 2.55158480e+00  9.06172508e-01 -1.68794625e+00  6.05694155e-02]
 [ 2.22044605e-16  1.85773636e+00  1.21079962e+00  8.96201767e-02]
 [ 2.22044605e-16  0.00000000e+00  8.31831547e-01 -7.93218484e-01]
 [ 2.22044605e-16  0.00000000e+00  0.00000000e+00 -1.08934981e+00]
 [-2.22044605e-16  0.00000000e+00  1.38777878e-17 -2.22044605e-16]]
[[-0.8220542  -0.88836068 -0.98763464  0.92419804]
 [ 0.25410707  0.19187334  0.13912237 -0.38191358]
 [ 0.3170379  -0.02688408  0.07226878  0.        ]
 [ 0.32609613  0.41626575  0.          0.        ]
 [-0.22979289  0.          0.          0.        ]]
[ 0.82306074  0.95486122  0.67935048 -0.46618939]
[ 1.23092437 -0.30491623  1.22477909  0.42795196]
